### ISSUE TITLE
你好，我有点好奇 commit 中的表情是每次提交时手打的吗，还是有插件支持？

### ISSUE THREAD

**Issue by liuc-c** [JustUndertaker/jx3_bot#1]

**Comment by JustUndertaker** [comment]
github支持emoji图标，直接输入就行了，可以参考网站：https://gitmoji.js.org/




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JustUndertaker/jx3_bot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月23日(星期四) 下午3:43
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[JustUndertaker/jx3_bot] 你好，我有点好奇 commit 中的表情是每次提交时手打的吗，还是有插件支持？ (#1)

**Comment by liuc-c** [comment]
谢谢
