### ISSUE TITLE
jx3_token应该如何获取？

### ISSUE THREAD

**Issue by Junnstoy** [JustUndertaker/jx3_bot#12]
在部署机器人后，其他功能都能正常使用，看说明ticket接口需要jx3_token，那jx3_token应该如何获取？

**Comment by JustUndertaker** [comment]
> 在部署机器人后，其他功能都能正常使用，看说明ticket接口需要jx3_token，那jx3_token应该如何获取？

jx3_token是访问高级功能的权限，需要找jx3api网站站长购买噢，好像是188永久，当然你可以用他的免费功能。

**Comment by Junnstoy** [comment]
> 

好的了解了，感谢！
