### ISSUE TITLE
看到回复，有没有比较详细的安装方式，linux的话对系统有没有要求

### ISSUE THREAD

**Issue by autunn** [JustUndertaker/jx3_bot#2]
你好，看到回复，有没有比较详细的安装方式，linux的话对系统有没有要求

**Comment by JustUndertaker** [comment]
> 你好，看到回复，有没有比较详细的安装方式，linux的话对系统有没有要求

具体的nb2和gocq安装启动方式请参考nonebot2和go-cqhttp的文档，需要配置的项目在README中都有详细的介绍了。
