### ISSUE TITLE
/service/price物价接口挂了

### ISSUE THREAD

**Issue by zyujs** [JustUndertaker/jx3_bot#5]
是否考虑用 https://www.jx3api.com/app/price 接口代替？

**Comment by JustUndertaker** [comment]
> 是否考虑用 https://www.jx3api.com/app/price 接口代替？

在做了在做了，不想画html啊……头秃

**Comment by JustUndertaker** [comment]
> 是否考虑用 https://www.jx3api.com/app/price 接口代替？

已修复，更新2.0版本。
